### ISSUE TITLE
Creating Prop - Error on add photo field

### ISSUE THREAD

**Issue by Juliasutton23** [Stars2Apples/Support#15]
When creating a prop all fields work fine except when adding the photo. When you tap the + sign it grays out and does not let you select the prop you want to add.  Thanks.

**Comment by ianclawson** [comment]
@Juliasutton23 thank you for bringing this to my attention! I found out what went wrong -- something changed in an Apple OS update -- and I'm uploading a fix now. An update with the fix should be available on the App Store within the next day or two.

Thank you again for reporting this!! 🙏

**Comment by ianclawson** [comment]
Closing this issue because a fix is now live in Version 1.5.2 on the App Store. Please update the app and reopen this issue if you find it hasn't been fixed. Thank you!
